apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv00001
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /home/data/persistent01
    server: 192.168.10.2
  persistentVolumeReclaimPolicy: Recycle
